### ISSUE TITLE
Extension asset is cached by CDN

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1135]
Note that this issue probably applies to the VS Code patch as a whole

For all assets that we store on the CDN we append a cache busting string (the git commit hash of that build) when requesting them, but that approach hasn't been copied across to the VS Code patch. VS Code uses a form of dynamic importing for downloading imported files as and when it needs them, so we need to apply it around that.

**Comment by seanparsons** [comment]
This should now be fixed by this: https://github.com/concrete-utopia/utopia/commit/e41e3903f3ae24fbd83c471824f72e4ecb715726

Which means that any request under the `/vscode` path should have Cloudfront defer to the origin server against the ETag header, returning a 304 up the chain if nothing has changed. This _should_ mean we get both browser and Cloudfront ETag based caching at the expense of more calls reaching the origin, but with no old content ever reaching the client.
