### ISSUE TITLE
Missing error message in this example project

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1169]
**Problem**
I made a mistake in my code (see if you can spot it). In codesandbox [here](https://codesandbox.io/s/vibrant-grass-hux0j?file=/src/App.js:0-1255) there's an error message. In Utopia [here](https://utopia.pizza/p/f864f875-glittery-tourmaline/) there's only a silent failure

Possibly related to #1155 (?)

cc @enidemi  :goodnews: is that we support Emotion's ThemeProvider, at least for single file projects. Thanks for reminding me to test that!

**Comment by balazsbajorics** [comment]
I'm closing this as a non-issue because: it's not a silent failure, it's actually that in Malte's project the scene starts at 500 pixels to the right :) 

Here's a version (with the removed jsx pragma since now master doesn't have the jsx pragma anymore) 
https://utopia.pizza/p/6fa0d993-glittery-tourmaline/

and here's a version with the scene moved to zero: https://utopia.pizza/p/f2894a5d-glittery-tourmaline/

**however**, we _should_ make a ticket for better autoscrolling the canvas @maltenuhn
