### ISSUE TITLE
saving the code file sometimes causes selection loss

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1310]
**Problem**
Occasionally, saving a code file modified and then saved (CMD+S) causes selection loss

**Video**
(I've included the copy/paste job of the sample project in case it has any bearing on anything, but the action starts at about 40 seconds in)

https://user-images.githubusercontent.com/2945037/119820342-463d1e00-bee9-11eb-9250-e347b47137dc.mp4

Redux Devtools json: https://www.dropbox.com/s/4z478wq6d035iro/devtools-selection-loss-after-save.json?dl=1

**Comment by seanparsons** [comment]
@maltenuhn Did the selection come back "immediately" after the end of this video? When I do this the selection is lost temporarily because of the typing triggering a canvas render to happen when the code is invalid, then once it becomes valid again the selection is restored. There's a slight delay because the code needs to be re-parsed in the worker which produces the bounds that are used for the selection.

**Comment by maltenuhn** [comment]
@seanparsons no, it only comes back when I move the cursor
