### ISSUE TITLE
Dark mode / Theming for the editor

### ISSUE THREAD

**Issue by cscheffauer** [concrete-utopia/utopia#1417]
It would be really awesome if a dark mode for the whole app could be added, or even theming support?

I would be free for working on this :)

**Comment by maltenuhn** [comment]
Hi, and nice to hear! We already have theoretical support for themes (in the sense that as it stands, there's only one), and actual support for VSCode themes (via the VSCode command palette, cmd+shift+P IIRC). Beyond that, there's basically three things that need to happen:

1. Extend theme support to our icons. We use PNGs inside `editor/light`, and in our codebase most of those references are hardcoded. Searching for the `<Icn>` and `<Icons. ...` helper components should get the 80/20.
2. Find the remaining hardcoded colours in the editor
3. Build a UI to switch it, probably in the settings panel in the left-hand menu

If you're interested in pairing up some or discussing more, we can find some overlap time, maybe on our Discord? Alternatively, super happy to give more detailed guidance by expanding on each of these here.

**Comment by mattwoodnyc** [comment]
I would love to see the options available in the design editor update, based on the design tokens of the theme.

For example, instead of a free-form text input for values such as margin, the user would select from a list of available options ("xs" | "sm" | "lg" | "xl")

- [ChakraUI](https://chakra-ui.com/docs/theming/theme#spacing)
- [ThemeUI Theme Specification](https://theme-ui.com/theme-spec)
- [Design System Checklist](https://www.designsystemchecklist.com/category/design-tokens/)

**Comment by maltenuhn** [comment]
> I would love to see the options available in the design editor update, based on the design tokens of the theme.

Hi there @mattwoodnyc . I believe this issue is about the theme / colour scheme for the editor / code editor itself, but better design system is something we're excited about - so I've taken the liberty to open a new issue for your comment at #1419 - and thanks for the specs for those systems, v helpful!

**Comment by cscheffauer** [comment]
@maltenuhn definitely interested in working on this. Can we discuss it further on Discord? (same username as here)
