### ISSUE TITLE
Error: "Span" is not part of the THREE namespace! 

### ISSUE THREAD

**Issue by alecmolloy** [concrete-utopia/utopia#468]
Code: (with three, react-three-fiber packages installed)

n.b. the error comes from importing `Box` from a file that has no export under that name, but the error is nonsensical.

```jsx
/** @jsx jsx */
import * as React from 'react'
import { Canvas } from 'react-three-fiber'
import { Scene, Storyboard, jsx } from 'utopia-api'
import { Box } from './index.js'

export var App = (props) => {
  return (
    <Canvas style={{ left: 38, top: 0 }}>
      <Box />
    </Canvas>
  )
}

export var storyboard = (
  <Storyboard>
    <Scene component={App} />
  </Storyboard>
)
```

Error: 
```
Error: "Span" is not part of the THREE namespace! Did you forget to extend it? See: https://github.com/react-spring/react-three-fiber#using-3rd-party-non-three-namespaced-objects-in-the-scene-graph
```

**Comment by Rheeseyb** [comment]
We should actually be getting an error complaining that the element type is invalid (since it is `undefined`). It seems that for some reason we're inserting a `span` in there _somewhere_, but only when rendering on the canvas. Most likely in `ui-jsx-canvas.tsx` when trying to find the correct element to render.
