### ISSUE TITLE
Implement and use `inspector:` from component API in H2 sample store

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#5290]
The Component API now includes an `inspector` field for specifying which parts of the inspector to render <https://github.com/concrete-utopia/utopia/blob/1db5de99e04b91a9c26cff3af50040018fa7b474/utopia-api/src/helpers/helper-functions.ts#L73>. That field isn't yet used, so we now need to honour the value provided when rendering the inspector for the selected component, and provide use it to suppress the style section for components that don't use it in the Sample Store project (`Column`, `Row`, the Remix and Hydrogen components)

Please contact Team Components if picking up this task.

**Comment by bkrmendy** [comment]
The plan:

- possible values for `inspector`: `"layout", "layout-system", "visual", "typography", "all"`

![Image](https://github.com/concrete-utopia/utopia/assets/16385508/c9e1fd8a-c9a6-487f-bcf5-62aeb97aa2b4)

- Class names, Style: controlled by `"visual"`
- Frame: controlled by `"frame"`
- Layout system: controlled by `"layout-system"`
- Container: bit of an edge case because of opacity, I'm going to use `"frame"` for it but open to ideas
- Type: controlled by `"typography"`
- Transforms, Background, Border, Shadow, Text Shadow: controlled by "`visual"`
