### ISSUE TITLE
Replacing a Placeholder from Column resulted in duplicate imports of Placeholder from different sources

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#5626]
There was Placeholder from within the project, and one imported from utopia-api. The issue came after replacing one of the placeholders, which seems to have renamed one of the imports perhaps?

**Comment by liady** [comment]
So - after investigating it seems like it's doing what it's supposed to do - 
Choosing `Placeholder` from the menu actually chooses the one from `Components`, and since there is an imported one from `utopia-api` it changes its name to `Placeholder_2` and adds it with that name.
Maybe the fix here is to have the sample project import `Placeholder` from `Components` as well, so there will be no duplication?

**Comment by maltenuhn** [comment]
> So - after investigating it seems like it's doing what it's supposed to do - Choosing `Placeholder` from the menu actually chooses the one from `Components`, and since there is an imported one from `utopia-api` it changes its name to `Placeholder_2` and adds it with that name. 

If memory serves (pls chime in here @gbalint and @balazsbajorics especially) we actually want the Placeholder component to _only_ live in the Utopia API

**Comment by liady** [comment]
In `components.utopia.js` the definitions bring the `Placholder` from `Components`, maybe that's the issue?
<img width="494" alt="image" src="https://github.com/concrete-utopia/utopia/assets/7003853/bfd8ad0e-1672-4c2e-9d77-e3afed911d58">

In any case seems like this might be an issue with the project config rather with the imports mechanism 🤔

**Comment by maltenuhn** [comment]
> In components.utopia.js the definitions are to import Placholder from Components

That does indeed seem like the issue here! Could you open a PR against the sample project?

**Comment by liady** [comment]
Fixed in https://github.com/concrete-utopia/hydrogen-november/pull/20
