### ISSUE TITLE
Hide expansion arrow when there's no component info. to show

### ISSUE THREAD

**Issue by lankaukk** [concrete-utopia/utopia#5750]
With the adjustments made in https://github.com/concrete-utopia/utopia/pull/5747, the remaining issue is that even when there is nothing to show inside the Component section in the inspector, we still show the expansion arrow. 

![Image](https://github.com/concrete-utopia/utopia/assets/47405698/b46127e3-4fe6-46bb-88a6-17960e29b0e8)

- [ ] Hide [this expansion arrow](https://github.com/concrete-utopia/utopia/blob/c18658103c171d3008c195e0138ad5a1ae45d6d2/editor/src/components/inspector/sections/component-section/component-section.tsx#L1261C4-L1268C24) in the component section header when there's no component info to show

**Comment by liady** [comment]
Note: since `PropertyControlsSection` decides whether there will be controls there (`ComponentSectionInner` which renders the expand button doesn't "know" that) - we need to extract this logic from `PropertControlsSection` somehow, or use a CSS trick where the controls section is always rendered (with a classname that toggles it `shown`/`hidden`) - and we use the `:has` selector in order to toggle the visibility of the expand button according to whether there is a controls section or not.
