### ISSUE TITLE
Mutating a prop in the component code does not change its value

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#5762]
If you mutate a prop in the component implementaion, the prop value does not change.

See https://utopia.pizza/p/4ec59759-chain-loaf/

![Image](https://github.com/concrete-utopia/utopia/assets/127662/c598a98d-238b-4185-9c19-df73a0e0ade7)

**Comment by Rheeseyb** [comment]
The problem here boils down to the way we run arbitrary code inside a component before the `return` statement. We wrap the code up into a function and run that, passing in the relevant parts of the scope here: <https://github.com/concrete-utopia/utopia/blob/ce371f808336a2e3fbe8ff3a0af443e3846c6c0a/editor/src/core/shared/javascript-cache.ts#L21-L46>

The problem is that although this is still compatible with mutating the relevant variables in scope, in the cases where the variable is a value (e.g. a string) or null / undefined, there is no way to update the reference there. What needs to happen is that the function wrapping the code also then needs to explicitly set the values in the scope.
