### ISSUE TITLE
Can not type space in some text elements

### ISSUE THREAD

**Issue by gbalint** [concrete-utopia/utopia#5784]
E.g. check `sehl-utopia` branch in the `hydrogen-may` project and navigate to `/products/builder-tote`

And try to edit text like here: https://screenshot.click/29-39-8dqak-7eklf.mp4

**Comment by liady** [comment]
This is due to Hydrogen's Typography using `text-wrap: pretty` as a defaut (check out `new/Text.js`)
<img width="156" alt="image" src="https://github.com/concrete-utopia/utopia/assets/7003853/0eab058d-b1c3-4a20-a84c-f450935ab456">

<img width="203" alt="image" src="https://github.com/concrete-utopia/utopia/assets/7003853/63c4dd6a-8c9c-4743-9ae9-2d55e726a22c">

This truncates and does not allow inserting spaces. If you override it with the prop `wrap='wrap'` on the heading, for example - you will see that it works.
