### ISSUE TITLE
Reimplement MultiColumn part of the Reviews component so it uses Flex

### ISSUE THREAD

**Issue by gbalint** [concrete-utopia/utopia#5807]
See

https://github.com/concrete-utopia/hydrogen-may/blob/sehl-utopia/app/routes/products.%24handle/sections/reviews.jsx#L48

[ ] Reimplement this with Flex
[ ] delete the MultiColumn component and its annotations

NOTE: do not change how it looks visually!

**Comment by liady** [comment]
Not sure it's fully possible to implement the `columns` css prop using `flex` properties, since the `columns` prop is dynamic - meaning that this markup
```html
<div style={{columns: 2}}>
  <div>first</div>
  <div>second</div>
```
will result in this:
|  |  |
| ------------- | ------------- |
| first | second |

but when you add another component
```html
<div style={{columns: 2}}>
  <div>first</div>
  <div>second</div>
  <div>third</div>
```
it will result in this:
|  |  |
| ------------- | ------------- |
| first | third |
| second | |

note that `second` move to the left column. I'm not sure that this kind of dynamic behavior can be fully implemented with flex.
