### ISSUE TITLE
Content is blinking in the hydrogen-may project

### ISSUE THREAD

**Issue by gbalint** [concrete-utopia/utopia#5841]
Some content is blinking/reloading/rerendering (remounting?) on all different kinds of interactions. E.g. see the tote bag here blinking on resizing something next to it:

https://screenshot.click/05-00-j4ybz-2nr75.mp4

Or simply when we switch editor mode:

https://screenshot.click/05-07-nwvug-d7e4g.gif

This may be connected to: https://github.com/concrete-utopia/utopia/issues/5834
It is suspicious that this is connected to live data coming from the loader. I also experienced that the mutation/resize observer fires in cases when there are no changes (e.g. during scrolling), that may be connected to this issue too.

**Comment by balazsbajorics** [comment]
@seanparsons is it just rerendering, or remounting? because I _think_ a rerender where React doesn't remove-re-add the DOM node should not result in an image being reloaded. I have a feeling (but not verified) that this is a remount happening somewhere, maybe because of a botched `key`, or something way more abstract, like the `React.element.type` losing reference because of a re-evaluation of arbitrary js

**Comment by gbalint** [comment]
Superseded by https://github.com/concrete-utopia/utopia/issues/5834
