### ISSUE TITLE
using the gap controls for the first time fails, even inside a div

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#5981]
**Problem**
1. The gap controls don't start from the currenltly observed gap, should
2. if there is no gap, the controls don't update the canvas correctly

Try it by selecting this inner div in the sample project, and using the gap control here.

NB it is already a known issue that the starting value for the gap isn't the actual value (in this case stemming from a tailwind class). But in addition to that, the first interaction with the gap control should - by setting style.gap - immediately apply, since `style` is more specific than `className`. However, it does not.

This appears to also be an issue for padding.
https://github.com/orgs/concrete-utopia/projects/6/views/1?pane=issue&itemId=67733608

**Comment by bkrmendy** [comment]
For posterity: I tried fixing this, the core problem is that the units of the padding value can only be read from the `style` prop or the tailwind class, because specialSizeMeasurements only has the size in `px`. Parsing out the actual values from the tailwind classes is far from a trivial job, so the fix for this should be rolled into the wider Tailwind support project.
