### ISSUE TITLE
Sometimes selection is lost after using component property controls

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#5982]
E.g. setting the padded property of a column.
I don't know how to reliably reproduce, but e.g. if you recreate the whole page building session of the demo there is high chance it is going to happen: https://paper.dropbox.com/doc/Building-the-Demo-Script--CRN8vYvyL8yZF6pJ6frX939uAg-Qtq5516kayWxUvkcCwOfT#:uid=430181461514264433643542&h2=Inserting-the-title-and-the-st

**Comment by balazsbajorics** [comment]
what I would try first is check the places in the code that trigger a print-> reparse cycle, and make sure that we print with the UIDs kept in, _not_ stripped away. In theory that should prevent any bugs that arise from a non-stable UID messing with selection. Once this is confirmed to fix the bug, we "just" need to prevent the editor from sending printed code with the UIDs over the vscode bridge.

(Come to think of it, maybe we could strip the UIDs right before sending it over the bridge, and otherwise keep it at all times?)

**Comment by maltenuhn** [comment]
I've moved this back because I don't know if we positively confirmed the root cause of this, _and_ that this is now definitively solved. Mentioned previously were a) the VSCode bridge (soon to be pulled down), and b) the new UUIDs (now 1000% more unique!). 

If either or both-in-conjunction is likely to have solved this, we should close this ticket (and open a new one if it happens again).
cc @Rheeseyb and @ruggi

**Comment by Rheeseyb** [comment]
Closing as I'm unable to repro this now
